[project]
authors = ["Wes B <wbrooks@ucdavis.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "workshop_ucdh_onboarding"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
r-base = ">=4.4.2,<4.5"
jupyter-book = ">=1.0.3,<2"
ghp-import = ">=2.1.0,<3"
